# wrangler.toml
name = "rmengine"
compatibility_date = "2025-03-09"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[durable_objects.bindings]]
name = "SESSION_STORE"
class_name = "SessionStore"

[[durable_objects.bindings]]
name = "MATCH_MAKER"
class_name = "MatchMaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionStore", "MatchMaker"]